# Page settings

baseURL = "https://justin-chiou-resume.netlify.com/"
languageCode = "en"
title = "Justin Chiou | Resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]

    author = "Justin Chiou"
    description = "Justin Chiou's Resume Site"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Justin Chiou"
        tagline = "Fullstack Developer"
        avatar = "profile.jpg"

    [params.contact]

        enable = true
        location = "Cincinnati, OH"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:6302048122"
        text = "(630) 204-8122"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:justin@wunderfund.co"
        text = "justin@wunderfund.co"

        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://justinchiou.me"
        text = "https://justinchiou.me"

    [params.skills]

        enable = true

        [[params.skills.list]]
        title = "Technical Foundation"

        [[params.skills.list.items]]
        details = "Wordpress (PHP)"

        [[params.skills.list.items]]
        details = "Django/Flask (Python)"

        [[params.skills.list.items]]
        details = "Firebase (Typescript)"

        [[params.skills.list.items]]
        details = "VueJS/NuxtJS (JS/TS)"

        [[params.skills.list.items]]
        details = "HTML5/CSS3"

        [[params.skills.list]]
        title = "Other Technologies"

        [[params.skills.list.items]]
        details = "Version Control (Git)"

        [[params.skills.list.items]]
        details = "Docker"

        [[params.skills.list.items]]
        details = "Python Anywhere"

        [[params.skills.list.items]]
        details = "Heroku"

        [[params.skills.list.items]]
        details = "Amazon AWS"

        [[params.skills.list.items]]
        details = "Matlab"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS, Biomedical Engineering"
        university = "Case Western Reserve University"
        dates = "2006 - 2010"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Ballroom Dancing"

        [[params.interests.list]]
        name = "Cooking"

        [[params.interests.list]]
        name = "Reading"

    [params.summary]
        enable = true
        text = "Aspiring Software Engineer with formal training in signals, systems and control analyses, hardware diagnostics, and GUI development, transitioned into software development and entrepreneurship. Skilled at all stages of software development cycle from architecture to testing and development, implementation, documentation and user interaction to security testing and rigor analyses based in compliance with the Securities Exchange Commission (SEC) and FINRA."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Co-Founder, Principal Architect"
        dates = "2020 - Present"
        company = "Wunderfund Health"
        details = "Emulated the Wunderfund Platform flagship SaaS product for purposes of soliciting marketability of startup companies in the biomedical engineering and pharmaceutical sector. Intentional aim was to provide additional investments in the the form of nonaccredited investors joining the cap table, as well as open up the segment to alternative offering types, such as CF and A+."

        [[params.experience.list]]
        title = "Co-Founder, CTO"
        dates = "2017 - Present"
        company = "Wunderfund, Inc."
        details = "Architected the flagship SaaS platform that allows an unaccredited investor to receive financial stakes within vetted startups. Compliant with the SEC and FINRA, the platform aims to provide legal marketability for companies at the pre-seed level, alongside adding automation of agreement binding and escrow transfer. Companies are able to create subscriptions for Regulation CF, A+, and D securities. Also performed Due Diligence leading to crowdfunding policy reforms on a state level for the State of Ohio."

        [[params.experience.list]]
        title = "Technology Consultant"
        dates = "2012 - 2019"
        company = "Thrivera"
        details = "Assisted in developing company-internal technologies and due diligence for various clientele. Collaborated with startup companies in the hyperlocal region on best practices for online marketing and VC Funding marketability. Provided workshops on leadership development and user experience leading to a new website for the Cincinnati Chamber of Commerce."

        [[params.experience.list]]
        title = "Junior Electrical Engineer"
        dates = "2011 - 2012"
        company = "GE Healthcare"
        details = "Improved Design of Experiments (DOE) for product development via B10 reliability for GEM suite products to above 150 days for both 1.5 and 3.0 Tesla field strength systems. Executed 2 major Control and Preventive Action engineering change reports that determined guard bands parameters for image quality failure modes using statistical Six Sigma methods."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Dancesport Software"
        link = "https://github.com/dancesportsoftware/das-frontend"
        tagline = "A frontend registration system that creates competitions for a new dancesport system. This system takes care of user registration, scheduling, heat times, scoresheets (post-comp), judge invites, role assignments, and administration of multiple competitions, all within the application."

        [[params.projects.list]]
        title = "Competition Registration System"
        link = "https://github.com/shadowlion/comp-registration"
        tagline = "A monolithic Django app that simulates a single ballroom competition. The app handles various functionalities tied in with calculating a user's ranking from the time they register to the time they compete. The app aims to handle the whole competitive operation of "

        [[params.projects.list]]
        title = "Praelatus"
        link = "https://github.com/praelatus"
        tagline = "An open-source issue ticketing service aimed at rivaling JIRA, using Python and Ansible."

    [params.portfolio]
    enable = true
    title = "Portfolio"

        [[params.portfolio.list]]

            [[params.portfolio.list.items]]
            text = "The Wunderfund Platform"
            url = "https://wunderfund.co"

            [[params.portfolio.list.items]]
            text = "Thrivera Consulting"
            url = "https://www.thrivera.io"

            [[params.portfolio.list.items]]
            text = "Ballroom East Dance Studio"
            url = "https://ballroomeast.com"

            [[params.portfolio.list.items]]
            text = "Aesthetics in Jewelry Website"
            url = "https://aestheticsinjewelry.com"

            [[params.portfolio.list.items]]
            text = "Wyzerr"
            url = "https://wyzerr.com"

            [[params.portfolio.list.items]]
            text = "TEDx Cincinnati"
            url = "https://tedxcincinnati.com"

    [params.social]

        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/shadowlion"
        title = "shadowlion"

        [[params.social.list]]
        icon = "fab fa-gitlab"
        url = "//gitlab.com/shadowlion"
        title = "shadowlion"

        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/justinchiou"
        title = "justinchiou"

        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/chiouzenone"
        title = "@chiouzenone"
