baseURL = 'https://shadowlion.github.io'
languageCode = 'en-us'
title = 'My Personal Website'
theme = "hugo-split-theme"

copyright = "&copy;2024 Justin Chiou"

[[params.visual.image]]
enable = true
file = "images/me.jpg"
position = "center center"
