name: Push to GitHub Pages on push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.69.0
          TARGET_REPO: shadowlion/personal
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: '-t hugo-devresume-theme'
          CNAME: shadowlion.github.io
